### ISSUE TITLE
vmecanumroverのオドメトリ値がおかしい

### ISSUE THREAD

**Issue by atinfinity** [vstoneofficial/mecanumrover_samples#4]
vmecanumroverが発行するオドメトリ（`rover_odo`）を確認すると値がおかしいように見受けられます。

### シミュレータ起動
```shell
git clone https://github.com/vstoneofficial/mecanumrover_samples.git
cd ..
catkin_make -DCMAKE_BUILD_TYPE=Release
source devel/setup.bash
roslaunch mecanumrover_samples vmecanumrover.launch
```

### rover_twist配信
```shell
rostopic pub /rover_twist geometry_msgs/Twist -r 1 -- '[1.0, 0.0, 0.0]' '[0.0, 0.0, -1.0]'
```

### odom購読
```shell
rostopic echo rover_odo
linear: 
  x: 0.839887589216
  y: 0.0212067812681
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: -0.0362106633746
---
linear: 
  x: 0.843559861183
  y: 0.0116153210402
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: -0.0359048156017
```

## 参考情報

姉妹プロジェクトの<https://github.com/vstoneofficial/megarover_samples>だとodomの値は問題なさそうです。

## シミュレータ起動
```shell
roslaunch megarover_samples vmegarover_with_empty_world.launch
```

### cmd_vel配信
```shell
rostopic pub /vmegarover/diff_drive_controller/cmd_vel geometry_msgs/Twist -r 1 -- '[1.0, 0.0, 0.0]' '[0.0, 0.0, 1.0]'
```

### odom購読

```
rostopic echo /vmegarover/diff_drive_controller/odom
header: 
  seq: 3855
  stamp: 
    secs: 77
    nsecs: 371000000
  frame_id: "odom"
child_frame_id: "base_footprint"
pose: 
  pose: 
    position: 
      x: 0.930948063996
      y: 1.44233480988
      z: 0.0
    orientation: 
      x: 0.0
      y: -0.0
      z: -0.848943057715
      w: -0.528484327826
  covariance: [0.001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000.0]
twist: 
  twist: 
    linear: 
      x: 0.999810289086
      y: 0.0
      z: 0.0
    angular: 
      x: 0.0
      y: 0.0
      z: 1.00309066901
  covariance: [0.001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000.0]
```

**Comment by vsfukatsu** [comment]
メカナムローバーのオドメトリは、メカナムローバー Ver 2.1 ROS制御モード取扱説明書の/rover_odoに関する説明(31ページ付近)にある通り、本製品のサンプルパッケージに含まれるノード「pub_odom」にて行われます。  
/launch/vmecanumrover.launchを実行後、`rosrun mecanumrover pub_odom`を実行すると、/odomにオドメトリがpublishされます。

**Comment by atinfinity** [comment]
@toshimori 説明が不十分で申し訳ありません。

このチケットで言及しているのは実機の系ではなく、Gazeboの系でrover_odoの値がおかしいのではないかということでした。rover_twistとrover_odoのtwistの値に大きな乖離があるのは意図通りでしょうか？

この質問の背景としては、Gazebo環境でvmegaroverを使ってgmappingを動かしてみたところ、車両をキー操作で動かす度にLRFのスキャンと地図がどんどんずれていくという現象がみられていて、その原因を探っていたところrover_odoの結果がおかしいのではないかということがわかりました（gmappingへ入力するodomへの変換は[pub_odom](https://github.com/vstoneofficial/mecanumrover_samples/blob/master/src/pub_odom.cpp)で実施することは認識しています）。

vmegarover（メガローバー）ではGazeboから得られるodomをそのまま使っているようですが、vmecanumrover（メカナムローバー）ではホイール回転数をもとに[vmecanum_odom](https://github.com/vstoneofficial/mecanumrover_samples/blob/master/src/vmecanum_odom.cpp)でrover_odoを計算しているように見受けられます。

**Comment by vsfukatsu** [comment]
ご指摘につきまして把握しました。補足いただきありがとうございます。  

メガローバーとメカナムローバーのオドメトリの差異につきまして、仕様上統一されておらず混乱を招き申し訳ありませんが、メカナムローバーのシミュレータでは実機がモータのエンコーダから得られた回転数からオドメトリを計算しているフローをそのまま再現しております。  
そのため、誤差についてはメガローバーのシミュレータより顕著に見られると思われます。  

ただ、ご提示いただいた数値より、実機の挙動からも割と大きめに乖離しておりましたので、こちらで検証いたしました。  
/src/vmecanum_odom.cppの10行目を`float w_rate=0.0625f;`に差し替えると、今よりも実機に近い挙動となります(まだ若干の差異はあります)。

**Comment by atinfinity** [comment]
@toshimori ご提示頂いた仮修正を適用したところlinear.xは近い値になっていること確認できました。一方でangular.zに関しては乖離が大きい問題がまだ残っているようです。

```
rostopic echo rover_odo
linear: 
  x: 0.994802176952
  y: 0.010379716754
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: -0.0271421035008
```
